
import { Item, Notification, UserProfile, ChatSession } from './types';

// Helper to generate slightly random locations around Pune (18.5204, 73.8567)
const getRandomLocation = () => {
  const baseLat = 18.5204;
  const baseLng = 73.8567;
  const latOffset = (Math.random() - 0.5) * 0.1; // +/- ~5km
  const lngOffset = (Math.random() - 0.5) * 0.1;
  return { lat: baseLat + latOffset, lng: baseLng + lngOffset };
};

const COLLEGES = ["COEP Tech", "PICT Pune", "VIT Pune", "MIT WPU", "Pune University", "AISSMS IOIT"];
const getRandomCollege = () => COLLEGES[Math.floor(Math.random() * COLLEGES.length)];

const rawCards: Item[] = [
  // --- ELECTRONICS & ITEMS ---
  {
    id: '1',
    title: "Logitech MX Master 3",
    description: "Top-tier productivity mouse. barely used.",
    category: 'Item',
    price: "₹4500",
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500&q=80",
    owner: "Rahul S.",
    ownerId: "mock_user_1",
    college: "COEP Tech",
    location: getRandomLocation(),
  },
  {
    id: '2',
    title: "Sony WH-1000XM4",
    description: "Industry leading noise canceling headphones.",
    category: 'Item',
    price: "₹12000",
    image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=500&q=80",
    owner: "Amit K.",
    ownerId: "mock_user_2",
    college: "PICT Pune",
    location: getRandomLocation(),
  },
  {
    id: '3',
    title: "iPad Air 4th Gen",
    description: "Great for digital notes and illustration.",
    category: 'Item',
    price: "₹35000",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500&q=80",
    owner: "Sneha P.",
    ownerId: "mock_user_3",
    college: "MIT WPU",
    location: getRandomLocation(),
  },
  {
    id: '4',
    title: "Scientific Calculator",
    description: "Standard engineering calc, exam approved.",
    category: 'Item',
    price: "₹400",
    image: "https://images.unsplash.com/photo-1587145820266-a5951ee6f620?w=500&q=80",
    owner: "Vikram R.",
    ownerId: "mock_user_4",
    college: "VIT Pune",
    location: getRandomLocation(),
  },
  {
    id: '5',
    title: "Drafter & Geometry Kit",
    description: "Full set for engineering drawing.",
    category: 'Item',
    price: "₹250",
    image: "https://images.unsplash.com/photo-1588508065123-287b28e013da?w=500&q=80",
    owner: "Pooja M.",
    ownerId: "mock_user_5",
    college: "COEP Tech",
    location: getRandomLocation(),
  },
  {
    id: '6',
    title: "Mechanical Keyboard",
    description: "Clicky blue switches, RGB backlit.",
    category: 'Item',
    price: "₹2500",
    image: "https://images.unsplash.com/photo-1595225476474-87563907a212?w=500&q=80",
    owner: "Arjun D.",
    ownerId: "mock_user_6",
    college: "Pune University",
    location: getRandomLocation(),
  },
  {
    id: '7',
    title: "Arduino Starter Kit",
    description: "Includes Uno, sensors, and breadboard.",
    category: 'Item',
    price: "₹1200",
    image: "https://images.unsplash.com/photo-1553406830-ef2513450d76?w=500&q=80",
    owner: "Meera L.",
    ownerId: "mock_user_7",
    college: "AISSMS IOIT",
    location: getRandomLocation(),
  },
  {
    id: '8',
    title: "Table Lamp",
    description: "Adjustable LED lamp for late night study.",
    category: 'Item',
    price: "₹300",
    image: "https://ikiru.in/cdn/shop/products/buy-table-lamp-adjustable-table-lamp-for-study-office-and-bedroom-by-kp-lamps-store-on-ikiru-online-store-1.jpg?v=1739204698",
    owner: "Karan J.",
    ownerId: "mock_user_8",
    college: "VIT Pune",
    location: getRandomLocation(),
  },
  {
    id: '9',
    title: "Extension Board",
    description: "4 sockets with surge protection.",
    category: 'Item',
    price: "₹200",
    image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=500&q=80",
    owner: "Rohit S.",
    ownerId: "mock_user_9",
    college: "PICT Pune",
    location: getRandomLocation(),
  },
  {
    id: '10',
    title: "Wireless Mouse",
    description: "Simple, reliable optical mouse.",
    category: 'Item',
    price: "₹600",
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500&q=80",
    owner: "Ananya B.",
    ownerId: "mock_user_10",
    college: "MIT WPU",
    location: getRandomLocation(),
  },
  {
    id: '11',
    title: "Gaming Monitor",
    description: "144Hz refresh rate, 24 inch.",
    category: 'Item',
    price: "₹8000",
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500&q=80",
    owner: "Siddharth M.",
    ownerId: "mock_user_11",
    college: "VIT Pune",
    location: getRandomLocation(),
  },
  {
    id: '12',
    title: "Bluetooth Speaker",
    description: "Portable speaker with deep bass.",
    category: 'Item',
    price: "₹1500",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&q=80",
    owner: "Varun K.",
    ownerId: "mock_user_12",
    college: "COEP Tech",
    location: getRandomLocation(),
  },
  {
    id: '13',
    title: "DSLR Camera Canon",
    description: "EOS 1500D with kit lens.",
    category: 'Item',
    price: "₹25000",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500&q=80",
    owner: "Neha G.",
    ownerId: "mock_user_13",
    college: "Pune University",
    location: getRandomLocation(),
  },
  {
    id: '14',
    title: "Graphics Tablet",
    description: "Wacom Intuos for digital art.",
    category: 'Item',
    price: "₹3000",
    image: "https://images.unsplash.com/photo-1586775490184-b79f0621891f?w=500&q=80",
    owner: "Aditya P.",
    ownerId: "mock_user_14",
    college: "PICT Pune",
    location: getRandomLocation(),
  },

  // --- STUDY MATERIALS ---
  {
    id: '15',
    title: "Calculus III Notes",
    description: "Detailed handwritten notes for M3.",
    category: 'Study',
    price: "20 Karma",
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500&q=80",
    owner: "Priya M.",
    ownerId: "mock_user_15",
    college: "COEP Tech",
    location: getRandomLocation(),
  },
  {
    id: '16',
    title: "H.C. Verma Physics Vol 1",
    description: "Classic physics textbook.",
    category: 'Study',
    price: "₹200",
    image: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=500&q=80",
    owner: "Rajesh K.",
    ownerId: "mock_user_16",
    college: "MIT WPU",
    location: getRandomLocation(),
  },
  {
    id: '17',
    title: "Organic Chemistry Notes",
    description: "Covers all reaction mechanisms.",
    category: 'Study',
    price: "Free",
    image: "https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=500&q=80",
    owner: "Simran T.",
    ownerId: "mock_user_17",
    college: "VIT Pune",
    location: getRandomLocation(),
  },
  {
    id: '18',
    title: "Engineering Graphics PYQs",
    description: "Previous year questions solved.",
    category: 'Study',
    price: "10 Karma",
    image: "https://images.unsplash.com/photo-1517842645767-c639042777db?w=500&q=80",
    owner: "Manoj D.",
    ownerId: "mock_user_18",
    college: "PICT Pune",
    location: getRandomLocation(),
  },
  {
    id: '19',
    title: "C++ Data Structures Book",
    description: "Standard reference for DSA.",
    category: 'Study',
    price: "₹350",
    image: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=500&q=80",
    owner: "Kavita S.",
    ownerId: "mock_user_19",
    college: "COEP Tech",
    location: getRandomLocation(),
  },
  {
    id: '20',
    title: "Medical Lab Coat",
    description: "White coat, size M, barely used.",
    category: 'Study',
    price: "₹300",
    image: "https://images.unsplash.com/photo-1584036561566-b93a90a6b262?w=500&q=80",
    owner: "Dr. A.",
    ownerId: "mock_user_20",
    college: "Pune University",
    location: getRandomLocation(),
  },
  {
    id: '21',
    title: "Architecture Portfolio",
    description: "Sample portfolio for reference.",
    category: 'Study',
    price: "Swap",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=500&q=80",
    owner: "Zara Q.",
    ownerId: "mock_user_21",
    college: "AISSMS IOIT",
    location: getRandomLocation(),
  },
  {
    id: '22',
    title: "GRE Prep Books",
    description: "Official guides and vocab flashcards.",
    category: 'Study',
    price: "₹500",
    image: "https://images.unsplash.com/photo-1491841550275-ad7854e35ca6?w=500&q=80",
    owner: "Nikhil J.",
    ownerId: "mock_user_22",
    college: "MIT WPU",
    location: getRandomLocation(),
  },
  {
    id: '23',
    title: "Law Entrance Guide",
    description: "CLAT preparation material.",
    category: 'Study',
    price: "₹200",
    image: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=500&q=80",
    owner: "Esha G.",
    ownerId: "mock_user_23",
    college: "COEP Tech",
    location: getRandomLocation(),
  },
  {
    id: '24',
    title: "MBA Case Studies",
    description: "Harvard business review cases.",
    category: 'Study',
    price: "50 Karma",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=500&q=80",
    owner: "Rohan B.",
    ownerId: "mock_user_24",
    college: "PICT Pune",
    location: getRandomLocation(),
  },
  {
    id: '25',
    title: "Psychology 101 Notes",
    description: "Intro to psych handwritten notes.",
    category: 'Study',
    price: "Free",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=500&q=80",
    owner: "Tanvi M.",
    ownerId: "mock_user_25",
    college: "VIT Pune",
    location: getRandomLocation(),
  },
  {
    id: '26',
    title: "UPSC History Maps",
    description: "Detailed maps for history optional.",
    category: 'Study',
    price: "₹100",
    image: "https://images.unsplash.com/photo-1524661135-423995f22d0b?w=500&q=80",
    owner: "Aryan V.",
    ownerId: "mock_user_26",
    college: "Pune University",
    location: getRandomLocation(),
  },
  {
    id: '27',
    title: "Biotech Lab Manual",
    description: "Standard protocols for lab work.",
    category: 'Study',
    price: "Swap",
    image: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=500&q=80",
    owner: "Sania K.",
    ownerId: "mock_user_27",
    college: "MIT WPU",
    location: getRandomLocation(),
  },

  // --- SKILLS ---
  {
    id: '28',
    title: "Python Tutoring",
    description: "Learn Python from scratch.",
    category: 'Skill',
    price: "Swap for Guitar",
    image: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=500&q=80",
    owner: "Mahesh Sir",
    ownerId: "mock_user_28",
    college: "PICT Pune",
    location: getRandomLocation(),
  },
  {
    id: '29',
    title: "Guitar Lessons",
    description: "Acoustic or electric basics.",
    category: 'Skill',
    price: "₹500/hr",
    image: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=500&q=80",
    owner: "Sam W.",
    ownerId: "mock_user_29",
    college: "COEP Tech",
    location: getRandomLocation(),
  },
  {
    id: '30',
    title: "Photography Basics",
    description: "Master manual mode on your DSLR.",
    category: 'Skill',
    price: "Swap for Notes",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500&q=80",
    owner: "Ankit R.",
    ownerId: "mock_user_30",
    college: "VIT Pune",
    location: getRandomLocation(),
  },
  {
    id: '31',
    title: "Yoga Instructor",
    description: "Morning yoga sessions.",
    category: 'Skill',
    price: "₹200/session",
    image: "https://images.unsplash.com/photo-1544367563-12123d8965cd?w=500&q=80",
    owner: "Divya P.",
    ownerId: "mock_user_31",
    college: "MIT WPU",
    location: getRandomLocation(),
  },
  {
    id: '32',
    title: "French Language Tutor",
    description: "A1/A2 level french tutoring.",
    category: 'Skill',
    price: "Swap for Math",
    image: "https://images.unsplash.com/photo-1527866959252-deab85ef7d1b?w=500&q=80",
    owner: "Aditi S.",
    ownerId: "mock_user_32",
    college: "PICT Pune",
    location: getRandomLocation(),
  },
  {
    id: '33',
    title: "Video Editing (Premiere)",
    description: "Learn to edit like a pro.",
    category: 'Skill',
    price: "₹1000/project",
    image: "https://images.unsplash.com/photo-1574717432707-c67805619ce9?w=500&q=80",
    owner: "Kabir H.",
    ownerId: "mock_user_33",
    college: "VIT Pune",
    location: getRandomLocation(),
  },
  {
    id: '34',
    title: "Resume Review",
    description: "Get your CV checked by a senior.",
    category: 'Skill',
    price: "Free",
    image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=500&q=80",
    owner: "Senior HR",
    ownerId: "mock_user_34",
    college: "COEP Tech",
    location: getRandomLocation(),
  },
  {
    id: '35',
    title: "Baking Classes",
    description: "Learn to bake cakes and cookies.",
    category: 'Skill',
    price: "Swap for Books",
    image: "https://images.unsplash.com/photo-1556910103-1c02745a30bf?w=500&q=80",
    owner: "Riya C.",
    ownerId: "mock_user_35",
    college: "Pune University",
    location: getRandomLocation(),
  },
  {
    id: '36',
    title: "Fitness Training",
    description: "Personalized workout plans.",
    category: 'Skill',
    price: "₹300/session",
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=500&q=80",
    owner: "Sahil F.",
    ownerId: "mock_user_36",
    college: "VIT Pune",
    location: getRandomLocation(),
  },
  {
    id: '37',
    title: "React JS Mentorship",
    description: "Master modern web development.",
    category: 'Skill',
    price: "50 Karma",
    image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=500&q=80",
    owner: "Dev L.",
    ownerId: "mock_user_37",
    college: "PICT Pune",
    location: getRandomLocation(),
  },
  {
    id: '38',
    title: "Digital Art Commission",
    description: "I will draw your portrait.",
    category: 'Skill',
    price: "₹500",
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=500&q=80",
    owner: "Tina A.",
    ownerId: "mock_user_38",
    college: "COEP Tech",
    location: getRandomLocation(),
  },
  {
    id: '39',
    title: "Chess Coaching",
    description: "Improve your opening game.",
    category: 'Skill',
    price: "Swap for C++",
    image: "https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=500&q=80",
    owner: "Vishy A.",
    ownerId: "mock_user_39",
    college: "MIT WPU",
    location: getRandomLocation(),
  },
  {
    id: '40',
    title: "Dance Choreography",
    description: "Learn bollywood or hip hop.",
    category: 'Skill',
    price: "₹400/hr",
    image: "https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=500&q=80",
    owner: "Remo D.",
    ownerId: "mock_user_40",
    college: "PICT Pune",
    location: getRandomLocation(),
  }
];

// High-fidelity shuffle (Fisher-Yates Algorithm)
const shuffleArray = <T>(array: T[]): T[] => {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
};

export const MOCK_CARDS = shuffleArray(rawCards);

export const INITIAL_PROFILE: UserProfile = {
  uid: 'u1', // Added uid
  name: 'Arjun Verma',
  college: 'COEP Tech',
  bio: 'CS Undergrad. Loves coding and coffee.',
  karma: 1250,
  sales: 14,
  earnings: '₹4,500',
  avatar: '', // Empty by default to show initials
};

export const INITIAL_NOTIFICATIONS: Notification[] = [
  { id: 1, text: "Match! Sneha wants your notes.", isRead: false },
  { id: 2, text: "Karma points updated (+50)", isRead: true },
];

export const MOCK_CHATS: ChatSession[] = [
  {
    id: '1',
    userId: 'u2',
    userName: 'Sneha P.',
    userAvatar: 'https://picsum.photos/200/200?random=10',
    lastMessage: 'Is 5 PM okay for the swap?',
    unreadCount: 2,
    timestamp: '10:30 AM',
    participants: ['u1', 'u2'], // Added participants
    messages: [
      { id: 'm1', senderId: 'u2', text: 'Hey Arjun! Saw your notes.', timestamp: '10:00 AM', isMe: false },
      { id: 'm2', senderId: 'me', text: 'Hi Sneha! Yes, still available.', timestamp: '10:05 AM', isMe: true },
      { id: 'm3', senderId: 'u2', text: 'Great. Can we meet at the library?', timestamp: '10:15 AM', isMe: false },
      { id: 'm4', senderId: 'u2', text: 'Is 5 PM okay for the swap?', timestamp: '10:30 AM', isMe: false },
    ]
  },
  {
    id: '2',
    userId: 'u3',
    userName: 'Amit S.',
    userAvatar: 'https://picsum.photos/200/200?random=11',
    lastMessage: 'Sure, let me check my schedule.',
    unreadCount: 0,
    timestamp: 'Yesterday',
    participants: ['u1', 'u3'], // Added participants
    messages: [
      { id: 'm1', senderId: 'me', text: 'Hi Amit, interested in Python tutoring.', timestamp: 'Yesterday', isMe: true },
      { id: 'm2', senderId: 'u3', text: 'Sure, let me check my schedule.', timestamp: 'Yesterday', isMe: false },
    ]
  },
  {
    id: '3',
    userId: 'u4',
    userName: 'Vikram R.',
    userAvatar: 'https://picsum.photos/200/200?random=12',
    lastMessage: 'The guitar lessons are on weekends.',
    unreadCount: 1,
    timestamp: 'Yesterday',
    participants: ['u1', 'u4'], // Added participants
    messages: [
      { id: 'm1', senderId: 'me', text: 'Do you teach beginners?', timestamp: 'Yesterday', isMe: true },
      { id: 'm2', senderId: 'u4', text: 'Yes! The guitar lessons are on weekends.', timestamp: 'Yesterday', isMe: false },
    ]
  },
  {
    id: '4',
    userId: 'u5',
    userName: 'Priya M.',
    userAvatar: 'https://picsum.photos/200/200?random=13',
    lastMessage: 'Calculated: ₹800 is final.',
    unreadCount: 0,
    timestamp: 'Mon',
    participants: ['u1', 'u5'], // Added participants
    messages: [
      { id: 'm1', senderId: 'u5', text: 'The price is fixed.', timestamp: 'Mon', isMe: false },
      { id: 'm2', senderId: 'u5', text: 'Calculated: ₹800 is final.', timestamp: 'Mon', isMe: false },
    ]
  }
];

export const COUPONS = [
  "Starbucks BOGO",
  "50% Off Canteen",
  "Free Xeroxing (50pgs)",
  "Amazon Prime 1 Month",
];
